import { NextRequest, NextResponse } from 'next/server'
import { promises as fs } from 'fs'
import path from 'path'

// Language-specific content templates
const LANGUAGE_CONTENT: Record<string, { 
  guide: string, 
  metaTitle: string, 
  metaDesc: string, 
  keyword: string, 
  wordCount: string,
  intro: string,
  whatIs: string,
  whyMatters: string,
  howTo: string,
  bestPractices: string,
  mistakes: string,
  advanced: string,
  tools: string,
  faq: string,
  conclusion: string,
  generated: string
}> = {
  en: { guide: 'The Complete Guide', metaTitle: 'Meta Title', metaDesc: 'Meta Description', keyword: 'Primary Keyword', wordCount: 'Word Count Target', intro: 'In this guide, we\'ll cover', whatIs: 'What is', whyMatters: 'Why', howTo: 'How to Get Started with', bestPractices: 'Best Practices for', mistakes: 'Common Mistakes to Avoid', advanced: 'Advanced Strategies', tools: 'Tools and Resources', faq: 'Frequently Asked Questions', conclusion: 'Conclusion', generated: 'Generated by SEO Content Guide on' },
  es: { guide: 'La Guía Completa', metaTitle: 'Título Meta', metaDesc: 'Meta Descripción', keyword: 'Palabra Clave Principal', wordCount: 'Objetivo de Palabras', intro: 'En esta guía, cubriremos', whatIs: 'Qué es', whyMatters: 'Por qué', howTo: 'Cómo Empezar con', bestPractices: 'Mejores Prácticas para', mistakes: 'Errores Comunes a Evitar', advanced: 'Estrategias Avanzadas', tools: 'Herramientas y Recursos', faq: 'Preguntas Frecuentes', conclusion: 'Conclusión', generated: 'Generado por SEO Content Guide el' },
  fr: { guide: 'Le Guide Complet', metaTitle: 'Titre Meta', metaDesc: 'Meta Description', keyword: 'Mot-clé Principal', wordCount: 'Objectif de Mots', intro: 'Dans ce guide, nous couvrirons', whatIs: 'Qu\'est-ce que', whyMatters: 'Pourquoi', howTo: 'Comment Débuter avec', bestPractices: 'Meilleures Pratiques pour', mistakes: 'Erreurs Courantes à Éviter', advanced: 'Stratégies Avancées', tools: 'Outils et Ressources', faq: 'Questions Fréquentes', conclusion: 'Conclusion', generated: 'Généré par SEO Content Guide le' },
  de: { guide: 'Der Vollständige Leitfaden', metaTitle: 'Meta-Titel', metaDesc: 'Meta-Beschreibung', keyword: 'Haupt-Keyword', wordCount: 'Wortzahl-Ziel', intro: 'In diesem Leitfaden behandeln wir', whatIs: 'Was ist', whyMatters: 'Warum', howTo: 'Erste Schritte mit', bestPractices: 'Best Practices für', mistakes: 'Häufige Fehler vermeiden', advanced: 'Fortgeschrittene Strategien', tools: 'Tools und Ressourcen', faq: 'Häufig Gestellte Fragen', conclusion: 'Fazit', generated: 'Erstellt von SEO Content Guide am' },
  it: { guide: 'La Guida Completa', metaTitle: 'Titolo Meta', metaDesc: 'Meta Descrizione', keyword: 'Parola Chiave Principale', wordCount: 'Obiettivo Parole', intro: 'In questa guida, tratteremo', whatIs: 'Cos\'è', whyMatters: 'Perché', howTo: 'Come Iniziare con', bestPractices: 'Migliori Pratiche per', mistakes: 'Errori Comuni da Evitare', advanced: 'Strategie Avanzate', tools: 'Strumenti e Risorse', faq: 'Domande Frequenti', conclusion: 'Conclusione', generated: 'Generato da SEO Content Guide il' },
  pt: { guide: 'O Guia Completo', metaTitle: 'Título Meta', metaDesc: 'Meta Descrição', keyword: 'Palavra-chave Principal', wordCount: 'Meta de Palavras', intro: 'Neste guia, abordaremos', whatIs: 'O que é', whyMatters: 'Por que', howTo: 'Como Começar com', bestPractices: 'Melhores Práticas para', mistakes: 'Erros Comuns a Evitar', advanced: 'Estratégias Avançadas', tools: 'Ferramentas e Recursos', faq: 'Perguntas Frequentes', conclusion: 'Conclusão', generated: 'Gerado por SEO Content Guide em' },
  nl: { guide: 'De Complete Gids', metaTitle: 'Meta Titel', metaDesc: 'Meta Beschrijving', keyword: 'Primair Trefwoord', wordCount: 'Woordtelling Doel', intro: 'In deze gids behandelen we', whatIs: 'Wat is', whyMatters: 'Waarom', howTo: 'Hoe te Beginnen met', bestPractices: 'Best Practices voor', mistakes: 'Veelgemaakte Fouten te Vermijden', advanced: 'Geavanceerde Strategieën', tools: 'Tools en Bronnen', faq: 'Veelgestelde Vragen', conclusion: 'Conclusie', generated: 'Gegenereerd door SEO Content Guide op' },
  ja: { guide: '完全ガイド', metaTitle: 'メタタイトル', metaDesc: 'メタ説明', keyword: 'プライマリキーワード', wordCount: '目標文字数', intro: 'このガイドでは以下を説明します', whatIs: 'とは', whyMatters: 'なぜ', howTo: 'の始め方', bestPractices: 'のベストプラクティス', mistakes: '避けるべき一般的な間違い', advanced: '高度な戦略', tools: 'ツールとリソース', faq: 'よくある質問', conclusion: '結論', generated: 'SEO Content Guideにより生成' },
  ko: { guide: '완전 가이드', metaTitle: '메타 제목', metaDesc: '메타 설명', keyword: '주요 키워드', wordCount: '목표 단어 수', intro: '이 가이드에서는 다음을 다룹니다', whatIs: '이란', whyMatters: '왜', howTo: '시작하는 방법', bestPractices: '모범 사례', mistakes: '피해야 할 일반적인 실수', advanced: '고급 전략', tools: '도구 및 리소스', faq: '자주 묻는 질문', conclusion: '결론', generated: 'SEO Content Guide에서 생성됨' },
  zh: { guide: '完整指南', metaTitle: '元标题', metaDesc: '元描述', keyword: '主要关键词', wordCount: '目标字数', intro: '在本指南中，我们将介绍', whatIs: '什么是', whyMatters: '为什么', howTo: '如何开始', bestPractices: '最佳实践', mistakes: '要避免的常见错误', advanced: '高级策略', tools: '工具和资源', faq: '常见问题', conclusion: '结论', generated: '由SEO Content Guide生成于' },
  ar: { guide: 'الدليل الشامل', metaTitle: 'عنوان الميتا', metaDesc: 'وصف الميتا', keyword: 'الكلمة المفتاحية الرئيسية', wordCount: 'هدف عدد الكلمات', intro: 'في هذا الدليل سنغطي', whatIs: 'ما هو', whyMatters: 'لماذا', howTo: 'كيف تبدأ مع', bestPractices: 'أفضل الممارسات لـ', mistakes: 'أخطاء شائعة يجب تجنبها', advanced: 'استراتيجيات متقدمة', tools: 'الأدوات والموارد', faq: 'أسئلة شائعة', conclusion: 'الخلاصة', generated: 'تم إنشاؤه بواسطة SEO Content Guide في' },
  ru: { guide: 'Полное Руководство', metaTitle: 'Мета Заголовок', metaDesc: 'Мета Описание', keyword: 'Основное Ключевое Слово', wordCount: 'Целевое Количество Слов', intro: 'В этом руководстве мы рассмотрим', whatIs: 'Что такое', whyMatters: 'Почему', howTo: 'Как начать с', bestPractices: 'Лучшие практики для', mistakes: 'Распространённые ошибки', advanced: 'Продвинутые стратегии', tools: 'Инструменты и ресурсы', faq: 'Часто задаваемые вопросы', conclusion: 'Заключение', generated: 'Создано SEO Content Guide' },
}

function getLangContent(lang: string) {
  return LANGUAGE_CONTENT[lang] || LANGUAGE_CONTENT['en']
}

export async function POST(request: NextRequest) {
  try {
    const { topic, language = 'en' } = await request.json()
    
    if (!topic) {
      return NextResponse.json({ error: 'Topic is required' }, { status: 400 })
    }

    const lang = getLangContent(language)

    // Read context files
    const contextPath = path.join(process.cwd(), 'context')
    let brandVoice = ''
    let features = ''
    let writingExamples = ''
    
    try {
      brandVoice = await fs.readFile(path.join(contextPath, 'brand-voice.md'), 'utf-8')
    } catch {}
    
    try {
      features = await fs.readFile(path.join(contextPath, 'features.md'), 'utf-8')
    } catch {}
    
    try {
      writingExamples = await fs.readFile(path.join(contextPath, 'writing-examples.md'), 'utf-8')
    } catch {}

    // Generate article content
    const article = `# ${topic}: ${lang.guide} [${new Date().getFullYear()}]

> **${lang.metaTitle}**: ${topic}: ${lang.guide} [${new Date().getFullYear()}]
> **${lang.metaDesc}**: Learn everything about ${topic.toLowerCase()} in this comprehensive guide. Discover best practices, actionable tips, and expert strategies to succeed.
> **${lang.keyword}**: ${topic.toLowerCase()}
> **${lang.wordCount}**: 2,500+ words
> **Language**: ${language.toUpperCase()}

---

${topic.split(' ')[0]} has become increasingly important in today's landscape. Whether you're just getting started or looking to level up your approach, this comprehensive guide will walk you through everything you need to know about ${topic.toLowerCase()}.

${lang.intro}:
- ${lang.whatIs} ${topic.toLowerCase()} is and why it matters
- Step-by-step instructions to get started
- Best practices from industry experts
- Common mistakes to avoid
- Advanced strategies for better results
- Frequently asked questions

Let's dive in.

## ${lang.whatIs} ${topic}?

${topic} refers to the practice of [define the core concept here]. At its core, it involves [explain the fundamental aspects].

Understanding ${topic.toLowerCase()} is crucial because:

1. **[Benefit 1]** - [Explanation of why this matters]
2. **[Benefit 2]** - [Explanation of why this matters]
3. **[Benefit 3]** - [Explanation of why this matters]

The landscape of ${topic.toLowerCase()} has evolved significantly over the past few years. What worked before may not work today, which is why staying current with best practices is essential.

## ${lang.whyMatters} ${topic} Matters

The importance of ${topic.toLowerCase()} cannot be overstated. Here's why it should be a priority:

### Impact on Results

When done correctly, ${topic.toLowerCase()} can lead to:
- Improved [outcome 1]
- Better [outcome 2]
- Increased [outcome 3]
- Enhanced [outcome 4]

### The Cost of Ignoring It

On the flip side, neglecting ${topic.toLowerCase()} can result in:
- Missed opportunities
- Falling behind competitors
- Wasted resources
- Suboptimal results

## ${lang.howTo} ${topic}

Getting started with ${topic.toLowerCase()} doesn't have to be complicated. Follow these steps:

### Step 1: [First Step Title]

Begin by [explain the first action to take]. This foundational step ensures you have [what this accomplishes].

**Action items:**
- [ ] [Specific task 1]
- [ ] [Specific task 2]
- [ ] [Specific task 3]

### Step 2: [Second Step Title]

Once you've completed step 1, move on to [explain the second action]. This involves [details about the process].

**Pro tip:** [Include an expert tip or insight here]

### Step 3: [Third Step Title]

With the foundation in place, you can now [explain the third action]. Focus on [key area to focus on].

### Step 4: [Fourth Step Title]

Continue building by [explain the fourth action]. At this stage, you should see [what results to expect].

### Step 5: [Fifth Step Title]

Finally, [explain the final action]. This completes the initial setup and positions you for [outcome].

## Best Practices for ${topic}

Based on industry research and expert insights, here are the best practices to follow:

### 1. [Best Practice Title]

[Explanation of the best practice and why it works]

**Example:** [Provide a concrete example]

### 2. [Best Practice Title]

[Explanation of the best practice and why it works]

**Example:** [Provide a concrete example]

### 3. [Best Practice Title]

[Explanation of the best practice and why it works]

**Example:** [Provide a concrete example]

### 4. [Best Practice Title]

[Explanation of the best practice and why it works]

### 5. [Best Practice Title]

[Explanation of the best practice and why it works]

## Common Mistakes to Avoid

Even experienced practitioners make these mistakes. Here's what to watch out for:

### Mistake 1: [Mistake Title]

**The problem:** [Explain what people do wrong]

**The fix:** [Explain how to do it correctly]

### Mistake 2: [Mistake Title]

**The problem:** [Explain what people do wrong]

**The fix:** [Explain how to do it correctly]

### Mistake 3: [Mistake Title]

**The problem:** [Explain what people do wrong]

**The fix:** [Explain how to do it correctly]

## Advanced Strategies

Ready to take your ${topic.toLowerCase()} to the next level? Try these advanced strategies:

### Strategy 1: [Advanced Strategy Title]

[Detailed explanation of the advanced strategy]

This approach works because [explain the reasoning].

### Strategy 2: [Advanced Strategy Title]

[Detailed explanation of the advanced strategy]

Implement this by [step-by-step breakdown].

### Strategy 3: [Advanced Strategy Title]

[Detailed explanation of the advanced strategy]

## Tools and Resources

Here are some helpful tools and resources for ${topic.toLowerCase()}:

### Tools
- **[Tool 1]** - [What it does and why it's useful]
- **[Tool 2]** - [What it does and why it's useful]
- **[Tool 3]** - [What it does and why it's useful]

### Resources
- [Resource 1 - Description]
- [Resource 2 - Description]
- [Resource 3 - Description]

## Frequently Asked Questions

### How long does it take to see results from ${topic.toLowerCase()}?

Results vary depending on [factors], but most people start seeing [outcomes] within [timeframe]. Consistency is key—focus on [key actions] and measure your progress regularly.

### What's the most important factor in ${topic.toLowerCase()}?

While many factors contribute to success, [key factor] tends to have the biggest impact. Focus on getting this right before optimizing other areas.

### Can beginners succeed with ${topic.toLowerCase()}?

Absolutely! ${topic} is accessible to anyone willing to learn and put in the effort. Start with the basics outlined in this guide and build from there.

### How much does ${topic.toLowerCase()} cost?

Costs vary widely depending on your approach. You can start with [free/low-cost options] and scale up as you see results. Budget [range] for [typical expenses].

### What are the biggest trends in ${topic.toLowerCase()} for ${new Date().getFullYear()}?

Key trends include:
- [Trend 1]
- [Trend 2]
- [Trend 3]

Stay current by [recommendation for staying updated].

## Conclusion

${topic} is a valuable skill that can significantly impact your [desired outcome]. By following the strategies and best practices outlined in this guide, you're well-positioned to [achieve specific result].

**Key takeaways:**
- [Takeaway 1]
- [Takeaway 2]
- [Takeaway 3]
- [Takeaway 4]

Ready to get started? [Call to action - what they should do next].

---

## SEO Optimization Checklist

- [ ] Primary keyword in H1 title
- [ ] Primary keyword in first 100 words
- [ ] Secondary keywords distributed throughout
- [ ] Meta title under 60 characters
- [ ] Meta description 150-160 characters
- [ ] H2 headings include relevant keywords
- [ ] Internal links added (2-3 minimum)
- [ ] External links to authoritative sources
- [ ] Images with alt text (if applicable)
- [ ] FAQ section with structured data potential

## Internal Linking Suggestions

Add internal links to:
- [Related guide/post 1]
- [Product/feature page if relevant]
- [Case study or example]

---
*Generated by SEO Content Guide on ${new Date().toLocaleDateString()}*
`

    // Save the draft
    const draftsPath = path.join(process.cwd(), 'drafts')
    const filename = `${topic.toLowerCase().replace(/\s+/g, '-')}-${new Date().toISOString().split('T')[0]}.md`
    
    try {
      await fs.mkdir(draftsPath, { recursive: true })
      await fs.writeFile(path.join(draftsPath, filename), article)
    } catch (e) {
      console.error('Error saving draft:', e)
    }

    return NextResponse.json({ 
      content: article,
      filename 
    })
  } catch (error) {
    console.error('Write error:', error)
    return NextResponse.json(
      { error: 'Failed to generate content' },
      { status: 500 }
    )
  }
}
